using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ESPSharp.Enums
{
    public enum ActorValues : int
    {
        None = -1,
        Aggression,
        Confidence,
        Energy,
        Responsibility,
        Mood,
        Strength,
        Perception,
        Endurance,
        Charisma,
        Intelligence,
        Agility,
        Luck,
        ActionPoints,
        CarryWeight,
        CriticalChance,
        HealRate,
        Health,
        MeleeDamage,
        DamageResistance,
        PoisonResistance,
        RadResistance,
        SpeedMultiplier,
        Fatigue,
        Karma,
        XP,
        PerceptionCondition,
        EnduranceCondition,
        LeftAttackCondition,
        RightAttackCondition,
        LeftMobilityCondition,
        RightMobilityCondition,
        BrainCondition,
        Barter,
        BigGuns_Unused,
        EnergyWeapons,
        Explosives,
        Lockpick,
        Medicine,
        MeleeWeapons,
        Repair,
        Science,
        Guns,
        Sneak,
        Speech,
        Survival,
        Unarmed,
        InventoryWeight,
        Paralysis,
        Invisibility,
        Chameleon,
        NightEye,
        Turbo,
        FireResistance,
        WaterBreathing,
        RadLevel,
        BloodyMess,
        UnarmedDamage,
        Assistance,
        ElectricResistance,
        FrostResistance,
        EnergyResistance,
        EMPResistance,
        IgnoreCrippledLimbs = 72,
        Dehydration,
        Hunger,
        SleepDeprivation,
        Damage
    }
}
