using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ESPSharp.Enums
{
    public enum FunctionType : uint
    {
        GetDistance = 1,
        GetLocked = 5,
        GetPOS,
        GetAngle = 8,
        GetStartingPos = 10,
        GetStartingAngle,
        GetSecondsPassed,
        GetActorValue = 14,
        GetCurrentTime = 18,
        GetScale = 24,
        IsMoving,
        IsTurning,
        GetLineOfSight,
        GetInSameCell = 32,
        GetDisabled = 35,
        MenuMode,
        GetDisease = 39,
        GetVampire,
        GetClothingValue,
        SameFaction,
        SameRace,
        SameSex,
        GetDetected,
        GetDead,
        GetItemCount,
        GetGold,
        GetSleeping,
        GetTalkedToPC,
        GetScriptVar = 53,
        GetQuestRunning = 56,
        GetStage = 58,
        GetStageDone,
        GetFactionRankDifference,
        IsAlarmed,
        IsRaining,
        GetAttacked,
        GetIsCreature,
        GetLockLevel,
        GetShouldAttack,
        GetInCell,
        GetIsClass,
        GetIsRace,
        GetIsSex,
        GetInFaction,
        GetIsID,
        GetFactionRank,
        GetGlobalValue,
        IsSnowing,
        GetDisposition,
        GetRandomPercent,
        GetQuestVariable = 79,
        GetLevel,
        GetArmorRating,
        GetDeadCount = 84,
        GetIsAlerted = 91,
        GetPlayerControlsDisabled = 98,
        GetHeadingAngle,
        IsWeaponOut = 101,
        IsTorchOut,
        IsShieldOut,
        IsFacingUp = 106,
        GetKnockedState,
        GetWeaponAnimType,
        IsWeaponSkillType,
        GetCurrentAIPackage,
        IsWaiting,
        IsIdlePlaying,
        GetMinorCrimeCount = 116,
        GetMajorCrimeCount,
        GetActorAggroRadiusViolated,
        GetCrime = 122,
        IsGreetingPlayer,
        IsGuard = 125,
        HasBeenEaten = 127,
        GetFatiguePercentage,
        GetPCIsClass,
        GetPCIsRace,
        GetPCIsSex,
        GetPCInFaction,
        SameFactionAsPC,
        SameRaceAsPC,
        SameSexAsPC,
        GetIsReference,
        IsTalking = 141,
        GetWalkSpeed,
        GetCurrentAIProcedure,
        GetTrespassWarningLevel,
        IsTrespassing,
        IsInMyOwnedCell,
        GetWindSpeed,
        GetCurrentWeatherPercent,
        GetIsCurrentWeather,
        IsContinuingPackagePCNear,
        CanHaveFlames = 153,
        HasFlames,
        GetOpenState = 157,
        GetSitting = 159,
        GetFurnitureMarkerID,
        GetIsCurrentPackage,
        IsCurrentFurnitureRef,
        IsCurrentFurnitureObj,
        GetDayOfWeek = 170,
        GetTalkedToPCParam = 172,
        IsPCSleeping = 175,
        IsPCAMurderer,
        GetDetectionLevel = 180,
        GetEquipped = 182,
        IsSwimming = 185,
        GetAmountSoldStolen = 190,
        GetIgnoreCrime = 192,
        GetPCExpelled,
        GetPCFactionMurder = 195,
        GetPCEnemyofFaction = 197,
        GetPCFactionAttack = 199,
        GetDestroyed = 203,
        HasMagicEffect = 214,
        GetDefaultOpen,
        GetAnimation = 219,
        IsSpellTarget = 223,
        GetVATSMode,
        GetPersuasionNumber,
        GetSandman,
        GetCannibal,
        GetIsClassDefault,
        GetClassDefaultMatch,
        GetInCellParam,
        GetVatsTargetHeight = 235,
        GetIsGhost = 237,
        GetUnconscious = 242,
        GetRestrained = 244,
        GetIsUsedItem = 246,
        GetIsUsedItemType,
        GetIsPlayableRace = 254,
        GetOffersServicesNow,
        GetUsedItemLevel = 258,
        GetUsedItemActivate,
        GetBarterGold = 264,
        IsTimePassing,
        IsPleasant,
        IsCloudy,
        GetArmorRatingUpperBody = 274,
        GetBaseActorValue = 277,
        IsOwner,
        IsCellOwner = 280,
        IsHorseStolen = 282,
        IsLeftUp = 285,
        IsSneaking,
        IsRunning,
        GetFriendHit,
        IsInCombat,
        IsInInterior = 300,
        IsWaterObject = 304,
        IsActorUsingATorch = 306,
        IsXBox = 309,
        GetInWorldspace,
        GetPCMiscStat = 312,
        IsActorEvil,
        IsActorAVictim,
        GetTotalPersuasionNumber,
        GetIdleDoneOnce = 318,
        GetNoRumors = 320,
        WhichServiceMenu = 323,
        IsRidingHorse = 327,
        IsInDangerousWater = 332,
        GetIgnoreFriendlyHits = 338,
        IsPlayersLastRiddenHorse,
        IsActor = 353,
        IsEssential,
        IsPlayerMovingIntoNewSpace = 358,
        GetTimeDead = 361,
        GetPlayerHasLastRiddenHorse,
        IsChild = 365,
        GetLastPlayerAction = 367,
        IsPlayerActionActive,
        IsTalkingActivatorActor = 370,
        IsInList = 372,
        GetHasNote = 382,
        GetHitLocation = 391,
        IsPC1stPerson,
        GetCauseofDeath = 397,
        IsLimbGone,
        IsWeaponInList,
        HasFriendDisposition = 403,
        GetVATSValue = 408,
        IsKiller,
        IsKillerObject,
        GetFactionCombatReaction,
        Exists = 415,
        GetGroupMemberCount,
        GetGroupTargetCount,
        GetObjectiveCompleted = 420,
        GetObjectiveDisplayed,
        GetIsVoiceType = 427,
        GetPlantedExplosive,
        IsActorTalkingThroughActivator = 430,
        GetHealthPercentage,
        GetIsObjectType = 433,
        GetDialogueEmotion = 435,
        GetDialogueEmotionValue,
        GetIsCreatureType = 438,
        GetInZone = 446,
        HasPerk = 449,
        GetFactionRelation,
        IsLastIdlePlayed,
        GetPlayerTeammate = 454,
        GetPlayerTeammateCount,
        GetActorCrimePlayerEnemy = 459,
        GetActorFactionPlayerEnemy,
        IsPlayerTagSkill = 462,
        IsPlayerGrabbedRef = 464,
        GetDestructionStage = 471,
        GetIsAlignment = 474,
        GetThreatRatio = 478,
        GetIsUsedItemEquipType = 480,
        GetConcussed = 489,
        GetMapMarkerVisible = 492,
        GetPermanentActorValue = 495,
        GetKillingBlowLimb,
        GetWeaponHealthPerc = 500,
        GetRadiationLevel = 503,
        GetLastHitCritical = 510,
        IsCombatTarget = 515,
        GetVATSRightAreaFree = 518,
        GetVATSLeftAreaFree,
        GetVATSBackAreaFree,
        GetVATSFrontAreaFree,
        GetIsLockBroken,
        IsPS3,
        IsWin32,
        GetVATSRightTargetVisible,
        GetVATSLeftTargetVisible,
        GetVATSBackTargetVisible,
        GetVATSFrontTargetVisible,
        IsInCriticalStage = 531,
        GetXPForNextLevel = 533,
        GetQuestCompleted = 546,
        IsGoreDisabled = 550,
        GetSpellUsageNum = 555,
        GetActorsInHigh = 557,
        HasLoaded3D,
        GetReputation = 573,
        GetReputationPct,
        GetReputationThreshold,
        IsHardcore = 586,
        GetForceHitReaction = 601,
        ChallengeLocked = 607,
        GetCasinoWinningStage = 610,
        PlayerInRegion = 612,
        GetChallengeCompleted = 614,
        IsAlwaysHardcore = 619
    }
}
